# Generated by Django 4.2 on 2023-10-11 23:42

import apps.user_profile.actions
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='', null=True, upload_to=apps.user_profile.actions.generate_photo_profile_path, verbose_name='Foto de perfíl')),
                ('address', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Dirección')),
                ('province', models.CharField(blank=True, choices=[('Pinar del Rio', 'Pinar Del Rio'), ('Artemisa', 'Artemisa'), ('Habana', 'Habana'), ('Mayabeque', 'Mayabeque'), ('Matanzas', 'Matanzas'), ('Villa Clara', 'Villa Clara'), ('Cienfuegos', 'Cienfuegos'), ('Sanctispíritus', 'Sanctispiritus'), ('Ciego de Avila', 'Ciego De Avila'), ('Camagüey', 'Camaguey'), ('Las Tunas', 'Las Tunas'), ('Granma', 'Granma'), ('Santiago de Cuba', 'Santiago De Cuba'), ('Holguín', 'Holguin'), ('Guantánamo', 'Guantanamo'), ('Isla de la Juventud', 'Isla De La Juventud')], default='', max_length=255, null=True, verbose_name='Provincia')),
                ('municipality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Municipio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfíl de usuario',
                'verbose_name_plural': 'Perfiles de usuarios',
            },
        ),
    ]
